# Generated by Django 4.0.2 on 2022-02-25 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('CountryID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Country_Name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelID', models.IntegerField(default=1)),
                ('Address', models.CharField(default='', max_length=100)),
                ('HotelName', models.CharField(default='', max_length=50)),
                ('FreeWifi', models.BooleanField(default=True)),
                ('Bar', models.BooleanField(default=True)),
                ('FitnessCenter', models.BooleanField(default=True)),
                ('Country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Country_ID', to='myapp.countries')),
            ],
            options={
                'unique_together': {('HotelID', 'Country_ID')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomID', models.IntegerField(default=1)),
                ('BookingPrice', models.IntegerField(default=1)),
                ('BedCount', models.IntegerField(default=1)),
                ('Furnished', models.BooleanField(default=True)),
                ('SmokingAllow', models.BooleanField(default=True)),
                ('TelevisionAvailable', models.BooleanField(default=True)),
                ('AirConditioned', models.BooleanField(default=True)),
                ('Hotel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hotel_ID', to='myapp.hotel')),
            ],
            options={
                'unique_together': {('RoomID', 'Hotel_ID')},
            },
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingID', models.IntegerField(default=1)),
                ('StartDate', models.DateField(default=datetime.date(2022, 2, 25))),
                ('EndDate', models.DateField(default=datetime.date(2022, 2, 25))),
                ('PersonName', models.CharField(default='', max_length=50)),
                ('CNIC', models.CharField(default='', max_length=13)),
                ('ContactNo', models.CharField(default='', max_length=15)),
                ('Room_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Room_ID', to='myapp.room')),
            ],
            options={
                'unique_together': {('BookingID', 'Room_ID')},
            },
        ),
    ]
